database:
  host: "localhost"
  port: 5432
  username: "admin"
  password: "admin"
  name: "go"
  ssl_mode: "disable"
  migrations_path: "./internal/storage/pgstorage/migrations"
  shards: 512

kafka:
  host: "localhost"
  port: 9092
  topic: "users_info"

redis:
  host: "localhost"
  port: 6379


web:
  host: "localhost"
  port: 8000
